server:
  port: 8001
eureka:
  server:
    eviction-interval-timer-in-ms: 3000
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://root:ghzx1234@127.0.0.1:8001/eureka/
  environment: product
  datacenter: cloud
spring:
  security:
    user:
      name: root
      password: ghzx1234
management:
  endpoint:
    health:
      show-details: always